apiVersion: apps/v1
kind: Deployment
metadata:
  name: pylogoutputapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pylogoutputapp
  template:
    metadata:
      labels:
        app: pylogoutputapp
    spec:
      containers:
        - name: pylogoutputapp
          image: sunqen/pylogoutputapp:latest