apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: exercises
  name: dwk-exercises-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: exercises-logoutput-strip@kubernetescrd
spec:
  rules:
  - http:
      paths:
      - path: /logoutput
        pathType: Prefix
        backend:
          service:
            name: log-output-svc
            port:
              number: 3456
      - path: /logoutput/pingpong
        pathType: Prefix
        backend:
          service:
            name: pingpong-app-svc
            port:
              number: 3457
