apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hashresponse-ingress
spec:
  rules:
  - http:
      paths:
      - path: /examples/hashresponse
        pathType: Prefix
        backend:
          service:
            name: hashresponse-svc
            port:
              number: 2345
