apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: the-project-staging

resources:
- ./../../base
- application.yaml
- nats-values.yaml

patches:
- path: todo-config.yaml

namePrefix: staging-

images:
- name: PROJECT/todo-app
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-app
  newTag: staging-6ace81fa5ebb5e5205c2250df428a9ff57bec9e3
- name: PROJECT/todo-app-writer
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-app-writer
  newTag: staging-6ace81fa5ebb5e5205c2250df428a9ff57bec9e3
- name: PROJECT/todo-backend
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-backend
  newTag: staging-6ace81fa5ebb5e5205c2250df428a9ff57bec9e3
- name: PROJECT/todo-broadcaster
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-broadcaster
  newTag: staging-6ace81fa5ebb5e5205c2250df428a9ff57bec9e3
- name: PROJECT/todo-cronjob
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-cronjob
  newTag: staging-6ace81fa5ebb5e5205c2250df428a9ff57bec9e3
