apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: the-project-staging

resources:
- ./../../base
- application.yaml

patches:
- path: todo-config.yaml

images:
- name: PROJECT/todo-app
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-app
  newTag: staging-0fd49ba9c04da9b623873d7701e1461e28e6085c
- name: PROJECT/todo-app-writer
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-app-writer
  newTag: staging-0fd49ba9c04da9b623873d7701e1461e28e6085c
- name: PROJECT/todo-backend
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-backend
  newTag: staging-0fd49ba9c04da9b623873d7701e1461e28e6085c
- name: PROJECT/todo-broadcaster
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-broadcaster
  newTag: staging-0fd49ba9c04da9b623873d7701e1461e28e6085c
- name: PROJECT/todo-cronjob
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-cronjob
  newTag: staging-0fd49ba9c04da9b623873d7701e1461e28e6085c
