apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: the-project-staging

resources:
- ./../../base

patches:
- path: todo-config.yaml

namePrefix: staging-

images:
- name: PROJECT/todo-app
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-app
  newTag: staging-bafa7a6810def05e6c8d0feac33abef7de7124b0
- name: PROJECT/todo-app-writer
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-app-writer
  newTag: staging-bafa7a6810def05e6c8d0feac33abef7de7124b0
- name: PROJECT/todo-backend
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-backend
  newTag: staging-bafa7a6810def05e6c8d0feac33abef7de7124b0
- name: PROJECT/todo-broadcaster
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-broadcaster
  newTag: staging-bafa7a6810def05e6c8d0feac33abef7de7124b0
- name: PROJECT/todo-cronjob
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-cronjob
  newTag: staging-bafa7a6810def05e6c8d0feac33abef7de7124b0
