apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cpu-usage-analysistemplate.yaml
- gateway-route.yaml
- log-config.yaml
- logdb.yaml
- log-output-rollout.yaml
- pingpong-app-rollout.yaml

images:
- name: PROJECT/log-output
  newName: sunqen/log-output
  newTag: 43cae25c38c8495b0f251724bda8c6cc179fdd63
- name: PROJECT/pingpong-app
  newName: sunqen/pingpong-app
  newTag: 43cae25c38c8495b0f251724bda8c6cc179fdd63
