apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-random-wiki-cron
spec:
  schedule: "0 * * * *"   # every hour
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: todo-cronjob
              image: sunqen/todo-cronjob:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: todo-config
