apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-app-claim
spec:
  volumeName: todo-app-pv
  storageClassName: image-pv-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi