apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: todo-app-claim
spec:
  storageClassName: image-pv-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi