apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tododb
spec:
  serviceName: tododb
  replicas: 1
  selector:
    matchLabels:
      app: tododb
  template:
    metadata:
      labels:
        app: tododb
    spec:
      containers:
        - name: tododb
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: tododb
            - name: POSTGRES_USER
              value: todouser
            - name: POSTGRES_PASSWORD
              value: todopass
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi