apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app-dep
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: todo-app-claim
      containers:
        - name: todo-app-writer
          image: sunqen/todo-app-writer:latest
          volumeMounts:
            - name: image-storage
              mountPath: /usr/src/app/image
        - name: todo-app
          image: sunqen/todo-app:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: image-storage
              mountPath: /usr/src/app/image
          env:
            - name: BACKEND_URL
              value: "http://todo-backend-svc:5000"