apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gke-manifests/cpu-usage-analysistemplate.yaml
  - gke-manifests/gateway-route.yaml
  - gke-manifests/log-config.yaml
  - gke-manifests/logdb.yaml
  - gke-manifests/log-output-rollout.yaml
  - gke-manifests/pingpong-app-rollout.yaml

images:
  - name: PROJECT/log-output
    newName: sunqen/log-output:b41bffc
  - name: PROJECT/pingpong-app
    newName: sunqen/pingpong-app:b41bffc
