apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dwk-exercises-ingress
spec:
  rules:
  - http:
      paths:
      # Log output app route
      - path: /
        pathType: Prefix
        backend:
          service:
            name: log-output-svc
            port:
              number: 3456

      # Ping-pong app route
      - path: /pingpong
        pathType: Prefix
        backend:
          service:
            name: pingpong-app-svc
            port:
              number: 3457