apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logdb
spec:
  serviceName: logdb
  replicas: 1
  selector:
    matchLabels:
      app: logdb
  template:
    metadata:
      labels:
        app: logdb
    spec:
      containers:
        - name: logdb
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: logdb
            - name: POSTGRES_USER
              value: loguser
            - name: POSTGRES_PASSWORD
              value: logpass
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi