apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: picsum-image-claim
spec:
  storageClassName: image-pv-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi