apiVersion: v1
kind: Secret
metadata:
    name: pixabay-apikey
data:
    API_KEY: ENC[AES256_GCM,data:fi+gWdbEF3aVLQIl+M2p6RfdZxPTu46QgXFXAdF2zqU4m46aXYxyRKA25PoLtFze,iv:nFZK12vTFmWEhSL3Hw1g1b4ESzmeicv0JNYP54EOtWY=,tag:5Pkm6PuU8QPySwv7tZZJtA==,type:str]
sops:
    age:
        - recipient: age1nzm89wrn2crf3xhl666zrvfpukgjl3qzud0tswyvrl7ttf03440qlkzqtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TEVxQjFidjlsaGpJZFpx
            bnBKMVJZVUVYK2I5RGJ1eFRaZUtMS2VzcW5zCnZib25ieDZ5WFI2M2xZaSt5bWJS
            L0x5WGFuSTBiWFpuZHVhRFJGODgzMXcKLS0tIFd6dzJjT1FXMFg3ZUNNYThvUnRr
            Q0dIMHB0S3pXM0VDQW9VOXdoVHYxL3MKpyCdIojLlRwVKS1hvo4BguHrx3YhLh2d
            ytoXWJIGKcHmlJCTZ2qdwn3V1BTzPDFRUG7dQqcUtHFbm27438gvzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T12:13:20Z"
    mac: ENC[AES256_GCM,data:P42kdGDeQxPSxFyA8TZ9L5BRbplc9L484t+O6YSS+04i4M21c7yK1yPsCinXk5l1FrAFfC/YiLrSmquOGclOSifHcy+DREstB8BAN2ti+ivOOgnfmjWuOsjlmsknE+k5G2ULJJjAifdOHrbv8n2ShhFWhAVcgrEKrSDKbRWHvC4=,iv:CZCRJqIW0uFXK4aEkadJjmKQ/qGY2h80cYKXMyFbR2k=,tag:CtH1aytgFcrSwaNp3qINmA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
