apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-grafana
  namespace: prometheus
type: Opaque
data:
  admin-user: YWRtaW4=          # base64 of "admin"
  admin-password: cGFzc3dvcmQ=  # base64 of your password
