apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: the-project-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:sunkken/devops_kubernetes.git"
    path: "the-project/overlays/prod"
    targetRevision: ">=4.8"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: the-project-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true