apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-dep
  labels:
    app: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      labels:
        app: debug
    spec:
      containers:
        - name: debug-shell
          image: ubuntu:24.04
          command: ["/bin/bash", "-c", "sleep infinity"]
          stdin: true
          tty: true
