apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-ubuntu
  labels:
    app: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      labels:
        app: debug
    spec:
      containers:
        - name: debug-shell
          image: sunqen/debug-bash-curl:bookworm-slim
          command: ["/bin/bash", "-c", "sleep infinity"]
          stdin: true
          tty: true
