services:
  todo-backend:
    build:
      context: ./todo-backend
    image: sunqen/todo-backend:latest
    env_file:
      - .env
    ports:
      - "5000:5000"

  todo-app:
    build:
      context: ./todo-app
    image: sunqen/todo-app:latest
    environment:
      TODO_APP_PORT: 3000
      TODO_APP_WORKDIR: /usr/src/app
      TODO_APP_BACKEND_URL: http://todo-backend:5000
    volumes:
      - image-volume:/usr/src/app/image
    env_file:
      - .env
    ports:
      - "1234:3000"
    depends_on:
      - todo-backend

  todo-app-writer:
    build:
      context: ./todo-app/picsum-writer
    image: sunqen/todo-app-writer:latest
    environment:
      TODO_APP_WORKDIR: /usr/src/app
    volumes:
      - image-volume:/usr/src/app/image
    env_file:
      - .env
    depends_on:
      - todo-app

volumes:
  image-volume:
