apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - gke-manifests/todo-gateway.yaml
  - gke-manifests/todo-config.yaml
  - gke-manifests/tododb.yaml
  - gke-manifests/todo-app-pvc.yaml
  - gke-manifests/todo-backend.yaml
  - gke-manifests/todo-app.yaml
  - gke-manifests/todo-cronjob.yaml

images:
  - name: PROJECT/todo-app
    newName: sunqen/todo-app
  - name: PROJECT/todo-app-writer
    newName: sunqen/todo-app-writer
  - name: PROJECT/todo-backend
    newName: sunqen/todo-backend
  - name: PROJECT/todo-cronjob
    newName: sunqen/todo-cronjob