apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-shell
  labels:
    app: debug-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-shell
  template:
    metadata:
      labels:
        app: debug-shell
    spec:
      containers:
      - name: debug-shell
        image: sunqen/debug-shell:latest
        imagePullPolicy: Always
        command: ["bash", "-c"]
        args:
          - |
            echo "Starting debug shell..."
            while true; do sleep 3600; done
        tty: true
        stdin: true