name: Build and publish dwk-app1

on:
  push:
    branches:
      - main
    paths:
      - 'examples/gke-part/dwk-app1/**'

jobs:
  build-publish:
    name: Build, Push, Release dwk-app1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: Build and publish dwk-app1
        working-directory: examples/gke-part/dwk-app1
        run: |-
          docker build --tag "sunqen/dwk1:$GITHUB_SHA" .
          docker push "sunqen/dwk1:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update dwk-app1 kustomization image
        working-directory: examples/gke-part/dwk-app1
        run: kustomize edit set image PROJECT/IMAGE=sunqen/dwk1:$GITHUB_SHA

      - name: commit dwk-app1 kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'examples/gke-part/dwk-app1/kustomization.yaml'
          message: New dwk-app1 version released ${{ github.sha }}