name: Build and Push Course Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Build and push log-output
      - name: Build and push log-output image
        uses: docker/build-push-action@v6
        with:
          context: ./log-output
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/log-output:latest

      # 5. Build and push todo-app
      - name: Build and push todo-app image
        uses: docker/build-push-action@v6
        with:
          context: ./todo-app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest
