name: Build and Push Course Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - todo-app
          - todo-app-writer
          - log-output-writer
          - log-output-reader
          - pingpong-app

    # Checkout repository and setup Docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Extract commit SHA for tagging
      - name: Extract short SHA
        id: vars
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

    # Detect which apps changed
      - name: Detect changed apps
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            todo-app: 'todo-app/**'
            todo-app-writer: 'todo-app/picsum_writer/**'
            log-output-writer: 'log-output/writer/**'
            log-output-reader: 'log-output/reader/**'
            pingpong-app: 'log-output/pingpong-app/**'

    # Set Docker build context
      - name: Set build context
        id: context
        run: |
          CONTEXT=${{ matrix.app == 'todo-app-writer' && 'todo-app/picsum_writer' || matrix.app }}
          echo "context=$CONTEXT" >> $GITHUB_OUTPUT

    # Build and push Docker image if the app changed
      - name: Build and push ${{ matrix.app }} image
        if: ${{ steps.changes.outputs[matrix.app] == 'true' }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ steps.context.outputs.context }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.app }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.app }}:${{ steps.vars.outputs.sha_short }}
          cache-from: type=gha,scope=node-deps
          cache-to: type=gha,mode=max,scope=node-deps